from python:3.13-bookworm
RUN apt-get update
RUN pip install --upgrade pip
RUN mkdir -p /data
WORKDIR /data
ADD requirements.txt /data
RUN pip install -r requirements.txt
RUN pip install requests

CMD ["python3", "ppo.py"]