from python:3.13-bookworm
RUN apt-get update
RUN pip install --upgrade pip
RUN mkdir -p /data
WORKDIR /data
RUN pip install torch[cpu] pettingzoo gymnasium requests
ADD requirements.txt /data
RUN pip install -r requirements.txt
RUN pip install tensorboard
RUN pip install pyarrow
RUN pip install scikit-learn
RUN pip install pandas

CMD ["python3", "ppo.py"]