import os
MAX_ACTIONS=int(os.getenv('MAX_ACTIONS', "1024"))
ONE_ACTION_ARRAY_SIZE=int(os.getenv('ONE_ACTION_ARRAY_SIZE', "1024"))
MAX_GAME_FEATURES_SIZE=int(os.getenv('MAX_GAME_FEATURES_SIZE', "10240"))